package main.enums.requests;

public enum ClientRequestType {
    IS_USERNAME_EXISTS,
    AUTHORIZE_USER,
    REGISTER_CLIENT,
    GET_USERS,
    GET_CARS,
    GET_REQUESTS,
    GET_USER_BY_USERNAME,
    DELETE_USER,
    DELETE_CAR,
    ADD_CAR,
    UPDATE_CAR,
    GET_TEST_DRIVES,
    DELETE_TEST_DRIVE,
    ADD_REQUEST,
    ADD_TEST_DRIVE,
    GET_CLIENTS,
    GET_TOP_THREE_CARS,
}
